document.getElementById("english_button").addEventListener("click", () => {
    document.getElementById("title").innerHTML = "Maya";
    
    const menu_links = document.querySelectorAll("nav > a");
    menu_links[0].innerHTML = "Home";
    menu_links[1].innerHTML = "History";
    menu_links[2].innerHTML = "Culture";
    menu_links[3].innerHTML = "Monuments";
    menu_links[4].innerHTML = "Bibliography";
    
    document.getElementById("wstep_p").innerHTML = "The Mayan civilization was one of the great Pre-Colombian civilizations, extending throughout the northern Central American tropical lowlands. The Maya excelled at agriculture, pottery, hieroglyph writing, calendar-making and mathematics, and left behind an astonishing amount of impressive architecture and symbolic artwork.";
    
    document.getElementById("historia_h2").innerHTML = "History";
    document.getElementById("historia_p").innerHTML = "As early as 1500 BCE the Maya had settled in villages and had developed an agriculture based on the cultivation of corn, beans, and squash. They began to build ceremonial centres, which had developed into cities containing temples, pyramids, palaces, courts for playing ball, and plazas.<br><br>Around 300 B.C., the Maya adopted a hierarchical system of government with rule by nobles and kings. This civilization developed into highly structured kingdoms. Their society consisted of many independent states, each with a rural farming community and large urban sites built around ceremonial centres.<br><br>From the late eighth through the end of the ninth century, something unknown happened to shake the Maya civilization to its foundations. One by one, the cities in the southern lowlands were abandoned, and by A.D. 900, Maya civilization in that region had collapsed. The reason for this mysterious decline is still unknown.<br><br>In the highlands of the Yucatan, a few Maya cities–such as Chichen Itza, Uxmal and Mayapán–continued to flourish in the later periods. By the time the Spanish invaders arrived, however, most Maya were living in agricultural villages, their great cities buried under a layer of rainforest green.<br><br>Maya history can be characterized as cycles of rise and fall: city-states rose in prominence and fell into decline, only to be replaced by others. It could also be described as one of continuity and change, guided by a religion that remains the foundation of their culture.";
    
    document.getElementById("kultura_h2").innerHTML = "Culture";
    document.getElementById("kultura_p").innerHTML = "Between 300BC - 300AC, the Maya civilisation continued to flourish as trade routes expanded along with advances in the cultivation of corn and the beginning of more complex agricultural practices, as well as construction of pyramids and urban centres. Maya society continued to develop based on an intricate cosmology that resulted in complex calendars, writing and astute mathematical calculations. <br><br>Innovation in arts, medicine and sciences, especially in the areas of mathematics and astronomy were phenomenal. They also established complex relations, alliances and intrigues with neighbouring city-states, and warfare and slave taking were not uncommon. <br><br>Human sacrifices were made on special occasions. Among the Maya, human sacrifice was not an everyday event but was essential to sanctify certain rituals, such as the inauguration of a new ruler, the designation of a new heir to the throne, or the consecration of an important new temple. The victims were often prisoners of war. At Chichén Itzá, victims would be painted blue, a color that is believed to have honored the god Chaak, and cast into a well. Additionally, near the site's ball court, there is a panel that shows a person being sacrificed. This may depict a ball-player from either the winning or losing team being killed after a game.";
    
    document.getElementById("zabytki_prolog_h2").innerHTML = "Visiting the ruins";
    document.getElementById("zabytki_prolog_p").innerHTML = "Travelling in Central American can be a bit complicated due to weather. In general there are two seasons, the rainy season and the dry season. Visiting during the rainy season, which runs from May to October, isn’t ideal as showers regularly come during the afternoons and last for hours. Additionally, it can get quite humid at this time of year, making your visit all the more taxing. During dry season it is at its hottest, especially during the months of April and May.<br><br>The other factor to keep in mind when planning your visit is the crowds of the high season. The tourist season runs from December through March, although it’s at its peak during the weeks either side of Christmas and Easter. Greater demand for accommodation at these times means prices are likely to be higher than other times of the year. All of this means that the best time to visit is during the months of February and March, when the weather is a little cooler and drier, and prices are slightly more affordable.";
    
    const zabytki = document.querySelectorAll(".card > p");
    zabytki[0].innerHTML = "In the heart of the Guatemalan jungle, surrounded by lush vegetation, lies one of the major sites of Mayan civilization. The ceremonial centre contains superb temples and palaces, and public squares accessed by means of ramps. Tikal is the largest and possibly the oldest of the Maya cities as the history of settlement stretches back as far as 1000 BC. If you feel like going for a wander in the jungle in search of ancient temples, Tikal is the place to do it.";
    zabytki[1].innerHTML = "Tulum, located in the south-eastern Mexico, was the last great city constructed and inhabited by the Mayan people between the thirteenth and fifteenth centuries. The greatest attraction at the Tulum Ruins is its location. Built on a bluff facing the rising sun, this ruin site is the only Maya settlement located on the beaches of the Caribbean. Thanks to it's location Tulum was also of great importance for sea trade. Today numerous structures remain, spread out over groomed lawns and oceanside cliffs. The Tulum ruins are located in the south-eastern Mexico, around 125km from the city of Cancún. These two places are well connected so getting there shouldn't be big of a problem. Whether seeking a scenic holiday or the chance to dive into rich Mexican culture or Mayan history, Tulum is an great travel destination.";
    zabytki[2].innerHTML = "Palenque is situated in the highland rainforest southern Mexico. This site dates to 700 A.D., it was a place of ceremony and burials. It is considered to be among the most important Mayan cities of olden times. Its population came close to almost one million inhabitants, which in turn lead to its decline since the natural resources of the area were just not enough to sustain everybody. Although the excavated portion of this archeological site is fairly small, the uniqueness of its setting and the quality of the stone carvings and treasures found inside the tombs really make Palenque shine.";
    zabytki[3].innerHTML = "The centuries-old ruins of Chichén Itzá undoubtedly are one of the most visited archeological sites and tourist attractions in Mexico. The city developed around 8th century AD and quickly became a major economic powerhouse in the region. It's ruins are listed as one of the ‘New Seven Wonders of the World’ and are home to towering temples, sacred sinkholes, and curious Mayan ballcourts. The stories that the city holds, and the displays of Maya astrological and architectural prowess, as well as its proximity to tourist hubs like Cancún and Playa del Carmen make it a great destination, make it a noteworthy stop.";
    zabytki[4].innerHTML = "Yaxchilán really is a lost city, still surrounded by jungle and vines. Only accessible by boat and situated deep in the Lacandón jungle, the journey to Yaxchilán is as enjoyable as the destination. The site contains impressive ruins, with palaces and temples bordering a large plaza. Yaxchilán is known for the large quantity of excellent sculpture at the site, such as the monolithic carved stelae and the narrative stone reliefs carved on lintels spanning the temple doorways.";
    zabytki[5].innerHTML = "Uxmal was once one of the most famous and powerful Mayan cities not only on the Yucatan but in the entire empire. Most of the construction work took places between the 7th and 9th century, and in its peak, around 25 000 people lived on the site. As the city was abandoned and didn’t have any value, the conquistadors didn’t pay their greedy attention to it and didn’t destroy it as many other Maya settlements. Thanks to this and the absence of tropical forests and exuberant Mexican vegetation, the architectural constructions and majestic complexes of buildings managed to survive here perfectly. Nowadays, they give tourists a full understanding of the lifestyle and daily routines of ancient tribes.";
    zabytki[6].innerHTML = "Edzná is a Maya archeological site in the north of the Mexican state of Campeche. <br><br>The most remarkable building at the site is the main temple located at the plaza. Built on a platform 40 m high, it provides a wide overview of the surroundings. <br><br>Another significant building located in the plaza is a ball court. Two parallel structures make up the ball court. The top rooms of the ball court were possibly used to store images of the gods associated with the events, along with items needed for the games.";
    zabytki[7].innerHTML = "You don't have to travel to Central America to witness Mayan heritage. British Museum holds impressive amount of Maya monuments and inscriptions.";
    
    
    const zabytkiDiv = document.querySelectorAll(".zabytki_div_text_div > p");
    zabytkiDiv[0].innerHTML = "In the heart of the Guatemalan jungle, surrounded by lush vegetation, lies one of the major sites of Mayan civilization. The ceremonial centre contains superb temples and palaces, and public squares accessed by means of ramps. Tikal is the largest and possibly the oldest of the Maya cities as the history of settlement stretches back as far as 1000 BC. If you feel like going for a wander in the jungle in search of ancient temples, Tikal is the place to do it.";
    zabytkiDiv[1].innerHTML = "Tulum, located in the south-eastern Mexico, was the last great city constructed and inhabited by the Mayan people between the thirteenth and fifteenth centuries. The greatest attraction at the Tulum Ruins is its location. Built on a bluff facing the rising sun, this ruin site is the only Maya settlement located on the beaches of the Caribbean. Thanks to it's location Tulum was also of great importance for sea trade. Today numerous structures remain, spread out over groomed lawns and oceanside cliffs. The Tulum ruins are located in the south-eastern Mexico, around 125km from the city of Cancún. These two places are well connected so getting there shouldn't be big of a problem. Whether seeking a scenic holiday or the chance to dive into rich Mexican culture or Mayan history, Tulum is an great travel destination.";
    zabytkiDiv[2].innerHTML = "Palenque is situated in the highland rainforest southern Mexico. This site dates to 700 A.D., it was a place of ceremony and burials. It is considered to be among the most important Mayan cities of olden times. Its population came close to almost one million inhabitants, which in turn lead to its decline since the natural resources of the area were just not enough to sustain everybody. Although the excavated portion of this archeological site is fairly small, the uniqueness of its setting and the quality of the stone carvings and treasures found inside the tombs really make Palenque shine.";
    zabytkiDiv[3].innerHTML = "The centuries-old ruins of Chichén Itzá undoubtedly are one of the most visited archeological sites and tourist attractions in Mexico. The city developed around 8th century AD and quickly became a major economic powerhouse in the region. It's ruins are listed as one of the ‘New Seven Wonders of the World’ and are home to towering temples, sacred sinkholes, and curious Mayan ballcourts. The stories that the city holds, and the displays of Maya astrological and architectural prowess, as well as its proximity to tourist hubs like Cancún and Playa del Carmen make it a great destination, make it a noteworthy stop.";
    zabytkiDiv[4].innerHTML = "Yaxchilán really is a lost city, still surrounded by jungle and vines. Only accessible by boat and situated deep in the Lacandón jungle, the journey to Yaxchilán is as enjoyable as the destination. The site contains impressive ruins, with palaces and temples bordering a large plaza. Yaxchilán is known for the large quantity of excellent sculpture at the site, such as the monolithic carved stelae and the narrative stone reliefs carved on lintels spanning the temple doorways.";
    zabytkiDiv[5].innerHTML = "Uxmal was once one of the most famous and powerful Mayan cities not only on the Yucatan but in the entire empire. Most of the construction work took places between the 7th and 9th century, and in its peak, around 25 000 people lived on the site. As the city was abandoned and didn’t have any value, the conquistadors didn’t pay their greedy attention to it and didn’t destroy it as many other Maya settlements. Thanks to this and the absence of tropical forests and exuberant Mexican vegetation, the architectural constructions and majestic complexes of buildings managed to survive here perfectly. Nowadays, they give tourists a full understanding of the lifestyle and daily routines of ancient tribes.";
    zabytkiDiv[6].innerHTML = "Edzná is a Maya archeological site in the north of the Mexican state of Campeche. <br><br>The most remarkable building at the site is the main temple located at the plaza. Built on a platform 40 m high, it provides a wide overview of the surroundings. <br><br>Another significant building located in the plaza is a ball court. Two parallel structures make up the ball court. The top rooms of the ball court were possibly used to store images of the gods associated with the events, along with items needed for the games.";
    zabytkiDiv[7].innerHTML = "You don't have to travel to Central America to witness Mayan heritage. British Museum holds impressive amount of Maya monuments and inscriptions.";
    
    document.querySelectorAll("div > button").forEach(element => {
        element.innerHTML = "See more";
    });
});